### PR TITLE
Port to Flutter 2 for null safety

### PR DESCRIPTION
**Pull request by jhass**
SSIA :) Would be awesome to have a new release with these changes.

Thank you for the great library!

### CODE REVIEW

**Comment by jhass** [comment]
Any chances?

**Comment by 2math** [comment]
Hi @jhass , I'm trying to use your fork as git plugin by the commit number, but got a weird error :
```
Error on line 1, column 7: "name" field doesn't match expected name "gesture_zoom_box".
  ╷
1 │ name: gesture_zoom_box_demo
  │       ^^^^^^^^^^^^^^^^^^^^^
```

Here is how I try to use it
```
  gesture_zoom_box:
      git:
        url: https://github.com/shichaohui/gesture_zoom_box
        ref: 49d33590e9031b4688bda30568cbe907d3958eb5
```

Same error if I use url: https://github.com/jhass/gesture_zoom_box

Is it possible to fix it?

Thanks in advance!

**Comment by jhass** [comment]
@2math It works for me like this:

https://github.com/jhass/insporation/blob/f94050c94c0311aa2563b28b019afcf17621c096/pubspec.yaml#L22-L26

**Comment by 2math** [comment]
@jhass , thank you!

**Comment by jhass** [comment]
Thanks for the merge! How about a (pre-) release? :)

**Comment by shichaohui** [comment]
published [v0.0.4](https://github.com/shichaohui/gesture_zoom_box/releases/tag/v0.0.4) to [pub](https://pub.dev/packages/gesture_zoom_box).

**Pull request merged**
